In [122]:
import numpy as np
import pandas as pd 
df = pd.read_csv(r"C:\PERSONAL\Data Sets\brain storke.csv")
df

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [123]:
df.shape

(4981, 11)

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [125]:
#data preprocessing
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [126]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
df['smoking_status']=label_encoder.fit_transform(df['smoking_status'])
df['smoking_status'].unique()

array([1, 2, 3, 0])

In [127]:
df['gender']=label_encoder.fit_transform(df['gender'])
df['gender'].unique()

array([1, 0])

In [128]:
df['ever_married']=label_encoder.fit_transform(df['ever_married'])
df['ever_married'].unique()

array([1, 0])

In [129]:
df['work_type']=label_encoder.fit_transform(df['work_type'])
df['work_type'].unique()

array([1, 2, 0, 3])

In [130]:
df['Residence_type']=label_encoder.fit_transform(df['Residence_type'])
df['Residence_type'].unique()
df

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          1   
1          1  80.0             0              1             1          1   
2          0  49.0             0              0             1          1   
3          0  79.0             1              0             1          2   
4          1  81.0             0              0             1          1   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          1   
4977       1  40.0             0              0             1          1   
4978       0  45.0             1              0             1          0   
4979       1  40.0             0              0             1          1   
4980       0  80.0             1              0             1          1   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  1             228.69  36.6               1       1  
1                  0             105.92  32.5               2       1  
2                  1             171.23  34.4               3       1  
3                  0             174.12  24.0               2       1  
4                  1             186.21  29.0               1       1  
...              ...                ...   ...             ...     ...  
4976               0              70.15  29.8               1       0  
4977               1             191.15  31.1               3       0  
4978               0              95.02  31.8               3       0  
4979               0              83.94  30.0               3       0  
4980               1              83.75  29.1               2       0  

[4981 rows x 11 columns]

In [131]:
#feature extraction
x = df[["age","heart_disease","avg_glucose_level","bmi","smoking_status"]] 
x


age  heart_disease  avg_glucose_level   bmi  smoking_status
0     67.0              1             228.69  36.6               1
1     80.0              1             105.92  32.5               2
2     49.0              0             171.23  34.4               3
3     79.0              0             174.12  24.0               2
4     81.0              0             186.21  29.0               1
...    ...            ...                ...   ...             ...
4976  41.0              0              70.15  29.8               1
4977  40.0              0             191.15  31.1               3
4978  45.0              0              95.02  31.8               3
4979  40.0              0              83.94  30.0               3
4980  80.0              0              83.75  29.1               2

[4981 rows x 5 columns]

In [132]:
#feature extraction
y = df.iloc[:,-1]
y

0       1
1       1
2       1
3       1
4       1
       ..
4976    0
4977    0
4978    0
4979    0
4980    0
Name: stroke, Length: 4981, dtype: int64

In [133]:
#model creation
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=42)
xtrain.shape
xtest.shape
ytrain.shape
ytest.shape

(997,)

In [139]:
#Create a Decision Tree Classifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(xtrain,ytrain)
#Get the accuracy score of the model
print('The accuracy of the Decision Tree Classifier is', round(accuracy_score(rfc.predict(xtest),ytest)*100,2),'%')
#Create the classification report
print(classification_report(ytest,rfc.predict(xtest)))

The accuracy of the Decision Tree Classifier is 94.08 %
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       943
           1       0.22      0.04      0.06        54

    accuracy                           0.94       997
   macro avg       0.58      0.51      0.52       997
weighted avg       0.91      0.94      0.92       997



In [135]:
#Confusion matrix
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(ytest,rfc.predict(xtest))
print(cm)


[[937   6]
 [ 53   1]]


In [137]:
prediction = np.array([[79.0,0,174.12,24.0,2]])
prediction_df = pd.DataFrame(prediction, columns=xtrain.columns)
print(rfc.predict(prediction_df))

[1]
